language: node_js
node_js:
  - 16
cache: npm
install:
  - npm install

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: build
      script:
        - npm run build
# script:
#   - npm test
#   - npm run build

# deploy:
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: build
#   on:
#     branch: master
